version: '3.8'
services:
  portfolio:
    image: nginx:alpine3.20-slim
    container_name: portfolio
    hostname: portfolio
    volumes:
      - ${PWD}/nginx:/usr/share/nginx
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    restart: unless-stopped
    networks:
      - npm-network

networks:
  npm-network:
    name: npm-network
    external: true
