version: '3.8'
services:
  portafolio:
    image: nginx:alpine3.20-slim
    container_name: portafolio
    hostname: portafolio
    volumes:
      - ./html:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
      - ./languages:/usr/share/nginx/html/languages
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    restart: unless-stopped
    networks:
      - npm-network

networks:
  npm-network:
    name: npm-network
    external: true
