/** Stack compartido ES/EN — iconos + nombres por idioma (no depende del JSON) */
window.PORTFOLIO_SKILLS = [
    {
        title: { es: 'DevSecOps & Cloud', en: 'DevSecOps & Cloud' },
        skills: [
            { icon: 'linux', name: { es: 'Linux', en: 'Linux' } },
            { icon: 'windows', name: { es: 'Windows Server', en: 'Windows Server' } },
            { icon: 'docker', name: { es: 'Docker', en: 'Docker' } },
            { icon: 'kubernetes', name: { es: 'Kubernetes', en: 'Kubernetes' } },
            { icon: 'terraform', name: { es: 'Terraform', en: 'Terraform' } },
            { icon: 'jenkins', name: { es: 'Jenkins', en: 'Jenkins' } },
            { icon: 'githubactions', name: { es: 'GitHub Actions', en: 'GitHub Actions' } },
            { icon: 'bitbucket', name: { es: 'Bitbucket', en: 'Bitbucket' } },
            { icon: 'aws', name: { es: 'AWS', en: 'AWS' } },
            { icon: 'cloudformation', name: { es: 'CloudFormation', en: 'CloudFormation' } },
            { icon: 'python', name: { es: 'Python', en: 'Python' } },
            { icon: 'bash', name: { es: 'Bash', en: 'Bash' } },
            { icon: 'powershell', name: { es: 'PowerShell', en: 'PowerShell' } },
            { icon: 'git', name: { es: 'Git', en: 'Git' } },
            { icon: 'ansible', name: { es: 'Ansible', en: 'Ansible' } },
        ],
    },
    {
        title: { es: 'Seguridad & Pentesting', en: 'Security & Pentesting' },
        skills: [
            { icon: 'sonarqube', name: { es: 'SonarQube', en: 'SonarQube' } },
            { icon: 'snyk', name: { es: 'Snyk', en: 'Snyk' } },
            { icon: 'owasp', name: { es: 'OWASP Dependency-Check', en: 'OWASP Dependency-Check' } },
            { icon: 'trivy', name: { es: 'Trivy', en: 'Trivy' } },
            { icon: 'burp', name: { es: 'Burp Suite', en: 'Burp Suite' } },
            { icon: 'zap', name: { es: 'OWASP ZAP', en: 'OWASP ZAP' } },
            { icon: 'metasploit', name: { es: 'Metasploit', en: 'Metasploit' } },
            { icon: 'nmap', name: { es: 'Nmap', en: 'Nmap' } },
            { icon: 'masscan', name: { es: 'Masscan', en: 'Masscan' } },
            { icon: 'wireshark', name: { es: 'Wireshark', en: 'Wireshark' } },
            { icon: 'iam', name: { es: 'IAM / RBAC', en: 'IAM / RBAC' } },
            { icon: 'pentesting', name: { es: 'Pentesting', en: 'Pentesting' } },
        ],
    },
    {
        title: { es: 'Observabilidad', en: 'Observability' },
        skills: [
            { icon: 'prometheus', name: { es: 'Prometheus', en: 'Prometheus' } },
            { icon: 'grafana', name: { es: 'Grafana', en: 'Grafana' } },
            { icon: 'zabbix', name: { es: 'Zabbix', en: 'Zabbix' } },
            { icon: 'logstash', name: { es: 'Logstash', en: 'Logstash' } },
            { icon: 'elasticsearch', name: { es: 'Elasticsearch', en: 'Elasticsearch' } },
            { icon: 'graylog', name: { es: 'Graylog', en: 'Graylog' } },
        ],
    },
    {
        title: { es: 'Infra & Redes', en: 'Infra & Networks' },
        skills: [
            { icon: 'proxmox', name: { es: 'Proxmox', en: 'Proxmox' } },
            { icon: 'vmware', name: { es: 'VMware', en: 'VMware' } },
            { icon: 'hyperv', name: { es: 'Hyper-V', en: 'Hyper-V' } },
            { icon: 'pfsense', name: { es: 'pfSense', en: 'pfSense' } },
            { icon: 'mikrotik', name: { es: 'MikroTik', en: 'Mikrotik' } },
            { icon: 'cisco', name: { es: 'Cisco', en: 'Cisco' } },
            { icon: 'vpn', name: { es: 'VPN / VLANs', en: 'VPN / VLANs' } },
            { icon: 'ai', name: { es: 'AI + LLM', en: 'AI + LLM' } },
        ],
    },
];
